language: python
python: 3.5
matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
script:
  - pip install cibuildwheel==0.6.0
  - cibuildwheel --output-dir wheelhouse
env:
  global:
    - CIBW_BEFORE_BUILD_LINUX="yum install -y mesa-libGLU-devel"
