language: python
python: 3.5
matrix:
  include:
    - sudo: required
      services:
        - docker
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
script:
  - pip install cibuildwheel==0.6.0
  - cibuildwheel --output-dir wheelhouse
  - |
      if [[ $TRAVIS_TAG ]]; then
        python -m pip install twine
        python -m twine upload wheelhouse/*.whl
      fi
env:
  global:
    - TWINE_USERNAME="mauve"
    - CIBW_BEFORE_BUILD_LINUX="yum install -y mesa-libGLU-devel"
